runtime: python39

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

entrypoint: gunicorn -b :$PORT app:app

env_variables:
  FLASK_ENV: "production"
  FLASK_APP: "app.py"
  PYTHONUNBUFFERED: "1"
  # These will be set through Google Cloud Console
  # GOOGLE_CLIENT_ID: ""
  # GOOGLE_CLIENT_SECRET: ""
  # OPENAI_API_KEY: ""
  # MONGODB_URI: ""

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always

vpc_access_connector:
  name: projects/vidpoint-411523/locations/us-central1/connectors/redis-connector
