steps:
  # Install dependencies
  - name: 'python:3.11'
    entrypoint: python
    args: ['-m', 'pip', 'install', '-r', 'requirements-app.txt', '--target', '.', '--no-deps']

  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--quiet']
    env:
      - 'GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID}'
      - 'GOOGLE_CLIENT_SECRET=${_GOOGLE_CLIENT_SECRET}'
      - 'OPENAI_API_KEY=${_OPENAI_API_KEY}'
      - 'MONGODB_URI=${_MONGODB_URI}'
      - 'FLASK_SECRET_KEY=${_FLASK_SECRET_KEY}'
      - 'FLASK_ENV=production'
      - 'FLASK_APP=app.py'
      - 'PYTHONUNBUFFERED=1'
      - 'SESSION_TYPE=redis'
      - 'REDIS_URL=redis://localhost:6379'
      - 'PORT=8080'

timeout: '1600s'
options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _GOOGLE_CLIENT_ID: '888239351498-jiim27rd47dngpccc1ed2a9pd7c7m082.apps.googleusercontent.com'
  _GOOGLE_CLIENT_SECRET: '${GOOGLE_CLIENT_SECRET}'
  _OPENAI_API_KEY: '${OPENAI_API_KEY}'
  _MONGODB_URI: '${MONGODB_URI}'
  _FLASK_SECRET_KEY: '${FLASK_SECRET_KEY}'
