steps:
  # Set up Python virtual environment and install dependencies
  - name: 'python:3.9'
    entrypoint: bash
    args:
      - '-c'
      - |
        python -m venv /workspace/venv
        . /workspace/venv/bin/activate
        pip install --upgrade pip setuptools wheel
        pip install -r requirements-minimal.txt

  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    secretEnv: ['GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET', 'OPENAI_API_KEY', 'MONGODB_URI', 'FLASK_SECRET_KEY']
    env:
      - 'SESSION_TYPE=redis'
      - 'REDIS_URL=redis://localhost:6379'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "$$GOOGLE_CLIENT_ID" > /workspace/_GOOGLE_CLIENT_ID
        echo "$$GOOGLE_CLIENT_SECRET" > /workspace/_GOOGLE_CLIENT_SECRET
        echo "$$OPENAI_API_KEY" > /workspace/_OPENAI_API_KEY
        echo "$$MONGODB_URI" > /workspace/_MONGODB_URI
        echo "$$FLASK_SECRET_KEY" > /workspace/_FLASK_SECRET_KEY
        
        gcloud app deploy \
          --quiet \
          --set-env-vars \
          GOOGLE_CLIENT_ID="$$(cat /workspace/_GOOGLE_CLIENT_ID)",\
          GOOGLE_CLIENT_SECRET="$$(cat /workspace/_GOOGLE_CLIENT_SECRET)",\
          OPENAI_API_KEY="$$(cat /workspace/_OPENAI_API_KEY)",\
          MONGODB_URI="$$(cat /workspace/_MONGODB_URI)",\
          FLASK_SECRET_KEY="$$(cat /workspace/_FLASK_SECRET_KEY)",\
          SESSION_TYPE=redis,\
          REDIS_URL=redis://localhost:6379

timeout: '1600s'
options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: projects/vidpoint/secrets/GOOGLE_CLIENT_ID/versions/latest
      env: 'GOOGLE_CLIENT_ID'
    - versionName: projects/vidpoint/secrets/GOOGLE_CLIENT_SECRET/versions/latest
      env: 'GOOGLE_CLIENT_SECRET'
    - versionName: projects/vidpoint/secrets/OPENAI_API_KEY/versions/latest
      env: 'OPENAI_API_KEY'
    - versionName: projects/vidpoint/secrets/MONGODB_URI/versions/latest
      env: 'MONGODB_URI'
    - versionName: projects/vidpoint/secrets/FLASK_SECRET_KEY/versions/latest
      env: 'FLASK_SECRET_KEY'
