steps:
  # Set up Python virtual environment and install dependencies
  - name: 'python:3.9'
    entrypoint: bash
    args:
      - '-c'
      - |
        python -m venv /workspace/venv
        . /workspace/venv/bin/activate
        pip install --upgrade pip setuptools wheel
        pip install -r requirements-minimal.txt

  # Create app.yaml with secrets
  - name: 'gcr.io/cloud-builders/gcloud'
    secretEnv: ['GOOGLE_CLIENT_SECRET', 'OPENAI_API_KEY', 'MONGODB_URI', 'FLASK_SECRET_KEY']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cat > app.yaml << EOF
        runtime: python39
        instance_class: F1
        automatic_scaling:
          target_cpu_utilization: 0.65
          min_instances: 1
          max_instances: 10
        entrypoint: gunicorn -b :$${PORT} app:app
        env_variables:
          FLASK_ENV: "production"
          FLASK_APP: "app.py"
          PYTHONUNBUFFERED: "1"
          GOOGLE_CLIENT_ID: "888239351498-jiim27rd47dngpccc1ed2a9pd7c7m082.apps.googleusercontent.com"
          GOOGLE_CLIENT_SECRET: "$${GOOGLE_CLIENT_SECRET}"
          OPENAI_API_KEY: "$${OPENAI_API_KEY}"
          MONGODB_URI: "$${MONGODB_URI}"
          FLASK_SECRET_KEY: "$${FLASK_SECRET_KEY}"
          SESSION_TYPE: "redis"
          REDIS_URL: "redis://localhost:6379"
        handlers:
        - url: /static
          static_dir: static
          secure: always
        - url: /.*
          script: auto
          secure: always
        vpc_access_connector:
          name: projects/vidpoint-411523/locations/us-central1/connectors/redis-connector
        EOF

  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']

timeout: '1600s'
options:
  logging: CLOUD_LOGGING_ONLY

# Add required IAM permissions
serviceAccount: 'projects/vidpoint-411523/serviceAccounts/vidpoint@vidpoint-411523.iam.gserviceaccount.com'
availableSecrets:
  secretManager:
    - versionName: projects/vidpoint-411523/secrets/GOOGLE_CLIENT_SECRET/versions/latest
      env: 'GOOGLE_CLIENT_SECRET'
    - versionName: projects/vidpoint-411523/secrets/OPENAI_API_KEY/versions/latest
      env: 'OPENAI_API_KEY'
    - versionName: projects/vidpoint-411523/secrets/MONGODB_URI/versions/latest
      env: 'MONGODB_URI'
    - versionName: projects/vidpoint-411523/secrets/FLASK_SECRET_KEY/versions/latest
      env: 'FLASK_SECRET_KEY'
