steps:
  # Set up Python virtual environment and install dependencies
  - name: 'python:3.9'
    entrypoint: bash
    args:
      - '-c'
      - |
        python -m venv /workspace/venv
        . /workspace/venv/bin/activate
        pip install --upgrade pip setuptools wheel
        pip install -r requirements-minimal.txt

  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - '-c'
      - |
        # Create app.yaml
        cat > app.yaml << EOF
        runtime: python39
        instance_class: F1
        
        automatic_scaling:
          target_cpu_utilization: 0.65
          min_instances: 1
          max_instances: 10
        
        entrypoint: gunicorn -b :8080 app:app
        
        env_variables:
          FLASK_ENV: ${_FLASK_ENV}
          FLASK_APP: ${_FLASK_APP}
          PYTHONUNBUFFERED: ${_PYTHONUNBUFFERED}
          GOOGLE_CLIENT_ID: ${_GOOGLE_CLIENT_ID}
          GOOGLE_CLIENT_SECRET: ${_GOOGLE_CLIENT_SECRET}
          OPENAI_API_KEY: ${_OPENAI_API_KEY}
          MONGODB_URI: ${_MONGODB_URI}
          FLASK_SECRET_KEY: ${_FLASK_SECRET_KEY}
          SESSION_TYPE: ${_SESSION_TYPE}
          REDIS_URL: ${_REDIS_URL}
          PORT: ${_PORT}
        
        handlers:
        - url: /static
          static_dir: static
          secure: always
        
        - url: /.*
          script: auto
          secure: always
        
        vpc_access_connector:
          name: projects/vidpoint/locations/us-central1/connectors/redis-connector
        EOF
        
        # Deploy
        gcloud app deploy --quiet

timeout: '1600s'
options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _FLASK_ENV: "production"
  _FLASK_APP: "app.py"
  _PYTHONUNBUFFERED: "1"
  _SESSION_TYPE: "redis"
  _REDIS_URL: "redis://localhost:6379"
  _PORT: "8080"
  _GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
  _GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
  _OPENAI_API_KEY: ${OPENAI_API_KEY}
  _MONGODB_URI: ${MONGODB_URI}
  _FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}

availableSecrets:
  secretManager:
    - versionName: projects/vidpoint/secrets/GOOGLE_CLIENT_ID/versions/latest
      env: 'GOOGLE_CLIENT_ID'
    - versionName: projects/vidpoint/secrets/GOOGLE_CLIENT_SECRET/versions/latest
      env: 'GOOGLE_CLIENT_SECRET'
    - versionName: projects/vidpoint/secrets/OPENAI_API_KEY/versions/latest
      env: 'OPENAI_API_KEY'
    - versionName: projects/vidpoint/secrets/MONGODB_URI/versions/latest
      env: 'MONGODB_URI'
    - versionName: projects/vidpoint/secrets/FLASK_SECRET_KEY/versions/latest
      env: 'FLASK_SECRET_KEY'
