steps:
  # Set up Python virtual environment and install dependencies
  - name: 'python:3.9'
    entrypoint: bash
    args:
      - '-c'
      - |
        python -m venv /workspace/venv
        . /workspace/venv/bin/activate
        pip install --upgrade pip setuptools wheel
        pip install -r requirements-minimal.txt

  # Deploy to App Engine with environment variables
  - name: 'gcr.io/cloud-builders/gcloud'
    secretEnv: ['GOOGLE_CLIENT_SECRET', 'OPENAI_API_KEY', 'MONGODB_URI', 'FLASK_SECRET_KEY']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud app deploy \
          --set-env-vars=^,^GOOGLE_CLIENT_ID=888239351498-jiim27rd47dngpccc1ed2a9pd7c7m082.apps.googleusercontent.com,\
          GOOGLE_CLIENT_SECRET=$${GOOGLE_CLIENT_SECRET},\
          OPENAI_API_KEY=$${OPENAI_API_KEY},\
          MONGODB_URI=$${MONGODB_URI},\
          FLASK_SECRET_KEY=$${FLASK_SECRET_KEY},\
          SESSION_TYPE=redis,\
          REDIS_URL=redis://localhost:6379

timeout: '1600s'
options:
  logging: CLOUD_LOGGING_ONLY

# Add required IAM permissions
serviceAccount: 'projects/vidpoint/serviceAccounts/vidpoint@vidpoint.iam.gserviceaccount.com'
availableSecrets:
  secretManager:
    - versionName: projects/vidpoint/secrets/GOOGLE_CLIENT_SECRET/versions/latest
      env: 'GOOGLE_CLIENT_SECRET'
    - versionName: projects/vidpoint/secrets/OPENAI_API_KEY/versions/latest
      env: 'OPENAI_API_KEY'
    - versionName: projects/vidpoint/secrets/MONGODB_URI/versions/latest
      env: 'MONGODB_URI'
    - versionName: projects/vidpoint/secrets/FLASK_SECRET_KEY/versions/latest
      env: 'FLASK_SECRET_KEY'
