services:
  - type: web
    name: vidpoint
    env: python
    region: oregon
    plan: starter
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg build-essential python3-dev
      pip install -r requirements.txt
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        value: 888239351498-jiim27rd47dngpccc1ed2a9pd7c7m082.apps.googleusercontent.com
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: MONGODB_URI
        fromDatabase:
          name: vidpoint-db
          property: connectionString
      - key: SMTP_SERVER
        value: mail.tekstreetz.com
      - key: SMTP_PORT
        value: 465
      - key: SMTP_USERNAME
        value: support@tekstreetz.com
      - key: SMTP_PASSWORD
        sync: false
      - key: FROM_EMAIL
        value: support@tekstreetz.com
      - key: SMTP_USE_SSL
        value: "true"
      - key: SQUARE_APP_ID
        sync: false
      - key: SQUARE_ACCESS_TOKEN
        sync: false
      - key: SQUARE_LOCATION_ID
        sync: false
      - key: SQUARE_ENVIRONMENT
        value: sandbox
      - key: SQUARE_WEBHOOK_SIGNING_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: vidpoint-data
      mountPath: /data
      sizeGB: 1

databases:
  - name: vidpoint-db
    databaseName: vidpoint
    plan: free
