services:
  - type: web
    name: vidpoint
    env: python
    region: oregon
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: STRIPE_PUBLIC_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: HUBTEL_CLIENT_ID
        value: ylmvenyc
      - key: HUBTEL_CLIENT_SECRET
        value: lojgrhvp
      - key: HUBTEL_MERCHANT_ID
        sync: false
      - key: MONGODB_URI
        fromDatabase:
          name: vidpoint-db
          property: connectionString
      - key: SMTP_SERVER
        value: mail.tekstreetz.com
      - key: SMTP_PORT
        value: 465
      - key: SMTP_USERNAME
        value: support@tekstreetz.com
      - key: SMTP_PASSWORD
        value: Pkmensah100%
      - key: FROM_EMAIL
        value: support@tekstreetz.com
      - key: SMTP_USE_SSL
        value: "true"
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: vidpoint-data
      mountPath: /data
      sizeGB: 1

databases:
  - name: vidpoint-db
    databaseName: vidpoint
    plan: free
